/*
 * Default.h
 *
 *  Created on: 24-okt-2010
 *      Author: B
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_



class Constants{
public:
	enum ACTIONS {BACK, MENU_ITEM_PLANNER, MENU_ITEM_MAP, MENU_ITEM_CHAT,
		MENU_ITEM_STARRED, MENU_ITEM_TRAFFIC, MENU_ITEM_OPTIONS,PLANNER_SEARCH};
	enum CUSTOMLISTITEMS {LIST_STATIONS,LIST_TIMES,LIST_DURATION,LIST_TRAINS};
};


#endif /* CONSTANTS_H_ */
